services:
  web:
    build: .
    volumes:
      - .:/src
    ports:
      - "4000:4000"
    environment:
      - LIMIT_POSTS=5
    command: jekyll serve --watch --incremental --force_polling --host 0.0.0.0
